[package]
name = "wasmi_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmi = "0.36.0"
wasmtime = {version = "25.0.1", features = ["runtime", "cranelift"] }

[lib]
crate-type = ["staticlib", "rlib"]
